# name字段是配置文件的描述
name: "GitHub Weekly Trending Bot"

# on字段是触发条件
on:
  # 在推送到master分支时会自动运行一次
  push:
    branches:
      - main
  schedule:
    # UTC0点30定期执行一次，跟北京时间大概相距8小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间8点30以后
    - cron: "0 21 * * *"

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境指定为最新版的 Ubuntu
    # 步骤
    steps:
      # 第一步 从代码仓库获取代码
      - name: Checkout
        uses: actions/checkout@v1

      # 第二步 配置安装python环境
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install and Build
        run: |
          npm install
          npm run js
          npm run ts

      # 第四步 提交
      - name: commit
        run: |
          git config --global user.email 763839938@qq.com
          git config --global user.name LuckRain7
          git add .
          git commit -m "update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          branch: main
